### ISSUE TITLE
User Friendly Error / Direct user (Mini Player)

### ISSUE THREAD

**Issue by jeanluchayes** [themagiulio/bandcamp-desktop#11]
If you click the Bandcamp Desktop Mini Player while on the front page or on your collection, it gives you this error:

![image](https://user-images.githubusercontent.com/9297247/102146104-6ba40700-3e36-11eb-8dcd-44be62d141a2.png)

And I understand why, the Mini Player is for use with an actual album, which works great.

If you could change that message to one that is more user Friendly, it could tell the user to "Please click an album to start using the Mini Player" or something like that.

Looking for other Quality of Life fixes, if possible.

**Comment by themagiulio** [comment]
Hi!
I agree with you, so I've added that feature in the version that I just released: [v2.3.2](
https://github.com/themagiulio/bandcamp-desktop/releases/tag/v2.3.2)

Thanks for your suggestion!
