### ISSUE TITLE
Bandcamp desktop on Mac not playing the next track from feed

### ISSUE THREAD

**Issue by ike1985** [themagiulio/bandcamp-desktop#14]
I am on Mac OSX high Sierra and I cannot get it to play the next track in the feed after the current track is done, it is not doing this automatically.

Thank You

**Comment by themagiulio** [comment]
This is a really strange behavior...
Can you please send a video of the player when the song is about to end?

**Comment by vivekteega** [comment]
On macOS Catalina 10.15.7 it seems to be working fine

**Comment by ike1985** [comment]
Here is the clip, note that it just never goes on to the next track:


https://user-images.githubusercontent.com/77642294/106034080-72ae6e00-60a0-11eb-83db-cc0d2536e45f.mov


I also suggest you install the bandcamp streamer extension in chrome, brave or firefox to checkout the interface it uses for the live feed player, it's superior and has volume, next track, previous track, etc controls.

**Comment by themagiulio** [comment]
@ike1985 you are using the default player. In order to use the Bandcamp Desktop Player you need to go to File > Mini Player and it should be opened inside an album page.

By the way it's a nice idea to create a browser addon!

**Comment by ike1985** [comment]
Here's what happens when I try to use the miniplayer on an album page:

![Screen Shot 2021-01-28 at 4 30 02 PM](https://user-images.githubusercontent.com/77642294/106201242-2a697b80-6186-11eb-8141-c1119ce2c26b.png)

also the feed is still broken and doesn't play the next track.  I almost never click on an album and listen to it all the way through on bandcamp, I and most other people (i'm guessing) just use the feed and if the feed can't play the next song the most important feature of the desktop app is broken IMO.  Thank you for all the hardwork and effort you put into this, I appreciate it.

**Comment by themagiulio** [comment]
The feed it's not broken, the app is still not programmed to do that.
I'll try to implement that feature in the next releases!

For the problem you are having, I think the cause is that the album link it's not a bandcamp one (bandcamp.com/etc...), I'll try to fix that too!
