### ISSUE TITLE
Mini player does not open

### ISSUE THREAD

**Issue by hubortje** [themagiulio/bandcamp-desktop#17]
Hey there,

I've got this error message, when trying to open the mini-player on an album page:

 A JavaScript error occurred in the main process
 
> Uncaught Exception:
 SyntaxError: Unexpected token u in JSON at position 0
 ....at JSON.parse (<anonymous>)
      at Request._callback
 (C:\Users\Username\Appdata\Local\Programs\bandcamp-desktop\resources\app.asar\src...:37)
    at Request.self.callback
 (C:\Users\Username\Appdata\Local\Programs\bandcamp-desktop\resources\app.asar\no...:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous>
 (C:\Users\Username\Appdata\Local\Programs\bandcamp-desktop\resources\app.asar\no...:10)
   at Request.emit (events.js:310:20)
   at IncomingMessage.<anonymous>
 (C:\Users\Username\Appdata\Local\Programs\bandcamp-desktop\resources\app.asar\no...:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
>    at processTicksAndRejections (internal/process/task_queues.js:84:21)

OS is Windows 10, current version 2.3.5 installed.

Cheers!

**Comment by themagiulio** [comment]
Hi, thanks for reporting the issue!
I'm facing the same problem. It's probably due to the fact that Bandcamp has changed the backend.
I'll try to update the app as soon as possible!

A temporary solution could be to use the "legacy" player. You can do that by going into  the app menu and deselecting Bandcamp Desktop Player which is inside File > Preferences.
Note that not all albums, eps, ... work with that method.

**Comment by themagiulio** [comment]
The problem has been solved in the new version.

**Comment by hubortje** [comment]
After updating to 2.3.6 it worked like a charm again, but now the same error applies.

**Comment by themagiulio** [comment]
The problem was the same of the last time. The new version should fix it again.

**Comment by hubortje** [comment]
Issue applies again.

**Comment by themagiulio** [comment]
Hi @hubortje,
I just tried to open the Mini Player on Windows 10 using the latest version and it works as expected.

**Comment by hubortje** [comment]
Hey, I restarted it a few times, and now it works again.
Thank you!

**Comment by themagiulio** [comment]
You're welcome!
I think that in the next version I'll put a script that will automatically check if the scraped string contains the urls of the songs.

**Comment by hubortje** [comment]
Issue applies again, even after some restarts.

**Comment by themagiulio** [comment]
Hey,
I've fixed another time the issue in the latest version!
