### ISSUE TITLE
Non-bandcamp-links opening up in Browser

### ISSUE THREAD

**Issue by hubortje** [themagiulio/bandcamp-desktop#20]
Hey there,

I love clicking through the "selling right now" section on the front page. Today it happened, that the clicked album opened up in the browser. As I tried reproducing the issue, all albums opened up in the App as they should. I realized, that the albums I clicked, led me to a [non-bandcamp link](https://shallnotfade.co.uk/album/tryna-take-my-man-ep).

Edit:
Tried something else: Searched for "Shall not fade" inside the App and clicked on the label, which then opened up in the browser.

Cheers

**Comment by themagiulio** [comment]
Hi,
thanks for submitting the issue. Noted! I'll try to handle non-bandcamp link in a better way in next versions.
Maybe a way could be scraping the page before redirecting and see if it contains sources from "bcbits.com"

**Comment by themagiulio** [comment]
Hey,
in the latest version non-bandcamp links are better handled, but I have to fix the web scraper in order to make it work.
I'll close this issue for now.
