### ISSUE TITLE
Mini Player Shortkey macOS

### ISSUE THREAD

**Issue by davidsjohnson** [themagiulio/bandcamp-desktop#26]
Great app, and I like the mini-player!  

But the current mini player shortkey `cmd-space` is already mapped to spotlight search in macOS.  It would be nice if the shortkey was configurable.

**Comment by themagiulio** [comment]
Hi, thanks for the suggestion!
I've just published a new release with this feature (v2.3.9). You need to go to File>Preferences>Change Keyboard Shortcuts and a json file should automatically be opened. Edit what you need and restart the app.
