### ISSUE TITLE
Can't Resize Window in Version 2

### ISSUE THREAD

**Issue by jeanluchayes** [themagiulio/bandcamp-desktop#3]
I can resize the windows vertically, but I can't resize the Window Horizontally.

**Comment by jeanluchayes** [comment]
Correction, I can resize the windows both Ways. However, I cannot resize the windows smaller than the current size it is. It's minimum width seems to be set.

**Comment by jeanluchayes** [comment]
It seems Min Width and Min Height are set in main.js, any reason why those specific values where chosen? Thanks.

**Comment by themagiulio** [comment]
Thanks for your help!
I had forgotten to remove that property, now it's fully resizable.
