### ISSUE TITLE
Python Script only build Linux AppImage

### ISSUE THREAD

**Issue by jjos1** [themagiulio/bandcamp-desktop#31]
Hi. 
I built the code with your Python Script but not matter what OS selects it always build the Linux AppImage. I'm on MacOs X Mojave.
Thanks

**Comment by themagiulio** [comment]
Hi, thanks for reporting this issue.
Apparently there's a problem with the library pynpm if used with versions of Python > 3.7.
By the way, at this point you are all set to build the software on your own. You can open the terminal inside the bandcamp-desktop folder and run the command:

`npm run-script build --mac`

You should find the compiled software inside the dist directory.

This is a temporary solution, I'll try to find a way to fix that.

**Comment by jjos1** [comment]
Thanks for the answer. 
I was also trying to build it manually cloning the repo and using 'npm run-script' as you describe in the Readme but no luck. When I try with the command you suggest I get the following error:
> bandcamp-desktop@2.4.0 build
> electron-builder build -l --publish never

sh: electron-builder: command not found

Any idea?
