### ISSUE TITLE
Login borked on Linux (Fedora 36)

### ISSUE THREAD

**Issue by RolesG** [themagiulio/bandcamp-desktop#35]
Downloaded the latest version (2.4.0) AppImage, it runs and the website loads but I can't login. I think it's failing at loading the CAPTCHA.

**Comment by themagiulio** [comment]
Hi, I use GNU/linux too (KDE neon) and it's running well. Does the website print some errors in the console?

**Comment by RolesG** [comment]
> Hi, I use GNU/linux too (KDE neon) and it's running well. Does the website print some errors in the console?

![error_iguess](https://user-images.githubusercontent.com/95465444/164048045-564a67b2-b171-420b-85e4-ba1f9c37e3be.png)
Just the one.

**Comment by themagiulio** [comment]
This error is due to the fact that you are using the latest version. It should not appear, but still...
Try to open the developer tools inside the app and see if you have some messages (View>Toggle Developer Tools).

**Comment by RolesG** [comment]
Where do I see the messages? I've toggled developer tools but I don't know what I'm looking for.

**Comment by themagiulio** [comment]
You have to click on the console tab. A chromium console should appear where error messages could be displayed.

![image](https://user-images.githubusercontent.com/18516031/164160735-d3285341-21c9-483d-adf5-8436d9c03c80.png)

**Comment by themagiulio** [comment]
Mhh that's weird. The shortcut should be ctrl+shift+i, but using the menu should work as well.
What if you try to build a rpm from source and install it? I don't think it would be different since the appimage is meant to be run in the same way on different distributions.

**Comment by RolesG** [comment]
I'll give it a shot.

**Comment by RolesG** [comment]
Building from source worked! I'm unsure as to proceed from here because I'm not familiar with npm.

**Comment by themagiulio** [comment]
I assume you already installed all the dependencies and built the application.
If you didn't changed the settings inside the package.json, you should see a dist folder in which you can find the built AppImage.

If you want to build the rpm you have to change the target in the package.json (build>linux>target) just replace AppImage with rpm and you are done. Run `npm build` and inside the dist folder you should find the rpm package.

**Comment by RolesG** [comment]
I had to build to an AppImage because apparently only Debian distros exist (it said that rpm wasn't installed and to use apt to install it)... anyway, it built fine, everything's working. Thanks for the help!

**Comment by themagiulio** [comment]
Oh right! In order to build those packages some additional dependencies are needed. By the way, I'm happy it worked!
