### ISSUE TITLE
Preferences - open on startup

### ISSUE THREAD

**Issue by jalcazo** [themagiulio/bandcamp-desktop#37]
Hi, feature request, I would like to auto-open bandcamp-desktop on launch windows.

Thnx and good work on your app

**Comment by themagiulio** [comment]
Hi, you can launch the app on startup by using the tools provided by your operating system of choice.

For Windows see: https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd
