### ISSUE TITLE
Windows Desktop Shortcut Named Incorrectly

### ISSUE THREAD

**Issue by jeanluchayes** [themagiulio/bandcamp-desktop#4]
After building the installer, (the exe) from npm and then installing it, it creates a desktop shortcut called:

bandcamp-desktop

Shouldn't it be:

Bandcamp Desktop

bandcamp Desktop

?

**Comment by jeanluchayes** [comment]
The name of the application on the upper left-hand corner of it is named:

Bandcamp

thus the shortcut should be named

Bandcamp Desktop

I believe

**Comment by jeanluchayes** [comment]
![image](https://user-images.githubusercontent.com/9297247/89131046-0e876480-d4d8-11ea-9361-4aabb18e6dae.png)

**Comment by themagiulio** [comment]
Thanks for your help,
with the last commit now the mainWindow's title is static.
For the other problem, I think I've fixed it by using the `productName` property, but I'm not sure since I can't build the software at the moment.

**Comment by jeanluchayes** [comment]
I'll build the windows version and check

**Comment by jeanluchayes** [comment]
![image](https://user-images.githubusercontent.com/9297247/89232188-f33e5700-d5b4-11ea-9325-a522b5a114f8.png)

verification complete, the Windows icon is correct and so is the title of the App.

You can close this issue.
