### ISSUE TITLE
Better Bandcamp Desktop Player

### ISSUE THREAD

**Issue by themagiulio** [themagiulio/bandcamp-desktop#9]
- [x] Add album image
- [x] Better songs list
- [x] Save set volume
- [x] Add Back and Forward buttons
- [ ] Ctrl(Cmd) + mouse click for opening album inside mini-player from wishlist and collection

**Comment by jeanluchayes** [comment]
Album Art for the Win!

**Comment by TipiT** [comment]
Just found this great project. Thank you and keep going, guys!
What about adding a back button to the list?

**Comment by themagiulio** [comment]
@TipiT thanks for your support!
It sounds great, I'm going to add it to the list of improvements :)

**Comment by ike1985** [comment]
How can I get this new version? will @viveteeka have to make a new file?

**Comment by hubortje** [comment]
I would like to propose a feature:
When you're in your collection and/or wishlist, it would be awesome to use e. g. ctrl-mouseclick combination, to open up an album in the mini-player from there, hence leaving out the detour via the album page itself.

**Comment by alexmaragko** [comment]
Is this equivalent to the android app, or to the website player? The reason I'm asking is because in the app the streaming quality is better compared to the website player (https://get.bandcamp.help/hc/en-us/articles/360007802334-What-format-quality-are-the-streams-on-Bandcamp-).

**Comment by themagiulio** [comment]
@alexmaragko it uses the mp3-128 format.
